# src/esther/PlatformBundle/Resources/config/routing.yml

esther_platform_home:
    path:      /{page}
    defaults:  { _controller: estherPlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*

esther_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: estherPlatformBundle:Advert:view }
    requirements:
        id: \d+

esther_platform_add:
    path:      /add
    defaults:  { _controller: estherPlatformBundle:Advert:add }

esther_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: estherPlatformBundle:Advert:edit }
    requirements:
        id: \d+

esther_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: estherPlatformBundle:Advert:delete }
    requirements:
        id: \d+