parameters:
#    esther_platform.example.class: esther\PlatflormBundle\Example

services:
#    esther_platform.example:
#        class: %esther_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
